# high-level pipeline configuration / overrides for process_df_global + evaluation + tuning
input_parquet: "C:/Users/gui/Documents/OpenClassrooms/Projet 7/df/df_global.parquet"
processed_output: "C:/Users/gui/Documents/credit_scoring/cache/df_final.parquet"
cache_dir: "C:/Users/gui/Documents/credit_scoring/cache"

# feature engineering (process_df_global)
n_select: 50
cor_val: 0.7
completeness: 85
impute: "median"   # options: median, mean, zero
percent_outliers: 1
variance_threshold: 0.01
target_col: "TARGET"

# dataframe evaluation
balances:
  - name: "initial"
    pos_frac: null
  - name: "25_75"
    pos_frac: 0.25
  - name: "50_50"
    pos_frac: 0.5
test_size: 0.2
random_state: 42

# algorithm evaluation
algorithms:
  - "logreg"
  - "random_forest"
  - "gradient_boosting"
  - "xgboost"   # will run only if xgboost installed

# tuning
tuning:
  trials: 30
  candidate_models:  # empty => auto-select best from evaluate_algorithm_potential
    - "random_forest"
    - "xgboost"
    - "logreg"
mlflow_experiment: "credit_scoring_pipeline_run"